# Generated by Django 4.2.3 on 2023-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipProgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
